### ISSUE TITLE
StdoutExporter: json output format

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#10]
Have a clean json output with an attached option flag in stdout exporter.

**Comment by luiscruz** [comment]
Hi @bpetit do you think this could be a good contribution for a newcomer? I'd be happy to help.

**Comment by bpetit** [comment]
Hi ! Thanks for your message ! It is a good first issue imho !
Don't hesitate to propose a PR :)

**Comment by luiscruz** [comment]
Excellent! I'll give it a try next week (hope it fits your plan/time constraints).

**Comment by bpetit** [comment]
No particular time constraint on that particular topic. Next week is perfect ! Thanks !

**Comment by luiscruz** [comment]
Hi there, just a quick update.
I haven't done this yet because I'm taking some time to learn Rust before doing any PR. (doing all the [Rust by Example](https://doc.rust-lang.org/stable/rust-by-example/) exercises)
Hope this is not an urgent issue. I'd like to keep it in my agenda, if you don't mind.

**Comment by bpetit** [comment]
No problem, no rush on this task. You can keep it. Thanks for your motivation ! Happy rusting !

**Comment by luiscruz** [comment]
Thanks! :)

**Comment by bpetit** [comment]
It seems like this feature will be redundant with the new JsonExporter:

- [PR](https://github.com/hubblo-org/scaphandre/pull/68)
- [FR](https://github.com/hubblo-org/scaphandre/issues/66)

@luiscruz would you like to jump on this PR and help review it instead ?
