### ISSUE TITLE
EKS Problem 

### ISSUE THREAD

**Issue by obito629** [hubblo-org/scaphandre#102]
Hi ,

i'm trying to install Scaphandre on my AWS EKS Cluster using Helm , but  i have this error

"MountVolume.SetUp failed for volume "powercap" : hostPath type check failed: /sys/class/powercap is not a directory"

## Environment

 Instance Type:                  m5.2xlarge
 Kernel Version:                 5.4.105-48.177.amzn2.x86_64
 OS Image:                        Amazon Linux 2
 Operating System:           linux
 Architecture:                    amd64

**Comment by demeringo** [comment]
Hi, @obito629 

My understanding is that today, public cloud vendor still do **not** expose the underlying Powercap/RAPL infrastructure that is necessary for Scaphandre to fetch measures. This explains that your container cannot access the specific directory.

See https://hubblo-org.github.io/scaphandre-documentation/compatibility.html

**Comment by bpetit** [comment]
Hi @demeringo @obito629 !

Thanks @demeringo you're absolutely right. We don't provide an out of the box solution for cloud providers as we need to discuss with the bare metal machine. Scaphandre would work if you run on AWS bare metal instances however. For virtual instance, there are 2 possible ways:

- pushing cloud providers to install scaphandre on their hypervisors so that you could benefit of the metrics in your virtual instances :)
- estimating the power consumption instead of measuring it, when we don't have access to the hardware, there is a project about that: https://github.com/hubblo-org/scaphandre/issues/25
