### ISSUE TITLE
Prometheus exporter: glitch happen with systemd process power consumption

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#19]
## Bug description

Glitch of unreal power consumption happen sometimes. Seems to be related specifically to systemd.

## To Reproduce

No specific procedure to reproduce. Run the prometheus exporter for quite a long time and hope you are lucky,.

## Screenshots

![2020-11-27_11-00](https://user-images.githubusercontent.com/906428/100436677-93097e80-3097-11eb-90ec-4d826338a42d.png)

## Environment

- OS: GNU/Linux 5.4.0-54-generic Ubuntu 20.04.1

**Comment by Mathieu-Coupe** [comment]
Same issue, but much more frequent.

![image](https://user-images.githubusercontent.com/1534517/104851588-3b003300-58f6-11eb-86dd-6a5cd45d8cf1.png)

**Comment by bpetit** [comment]
Who, super strange :flushed:
thanks for reporting !

**Comment by bpetit** [comment]
what is the exact request you used for your graph ?

**Comment by Mathieu-Coupe** [comment]
> what is the exact request you used for your graph ?

[export.zip](https://github.com/hubblo-org/scaphandre/files/5828593/export.zip)

I've clone the grafana dashboard and updated one of the "X power consumption" graph to : 
> scaph_process_power_consumption_microwatts{exe=~"systemd.*"} / 1000000

I've narrowed the filter to 
> scaph_process_power_consumption_microwatts{cmdline=~"--user.*systemd.*"} / 1000000

meaning that the processes that generate these high power are the "/lib/systemd/systemd --user" that are the root of one user session.

I've attached an export generated by the grafana query inspector.

Also, the cmdline content seems inverted as it reads "--user /lib/systemd/systemd" instead of "/lib/systemd/systemd --user" (and also missing space between args)

**Comment by bpetit** [comment]
Could you paste your CPU model from /proc/cpuinfo, the result of `uname -r` and you linux distribution and its version please ?

**Comment by Mathieu-Coupe** [comment]
This is a Ubuntu 20.10 distro running on a Core i3-7100. This processor has a TDP of 51W.

> $ uname -r
> 5.8.0-25-generic

> $ cat /proc/cpuinfo
> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 158
> model name      : Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
> stepping        : 9
> microcode       : 0xd6
> cpu MHz         : 2099.251
> cache size      : 3072 KB
> physical id     : 0
> siblings        : 4
> core id         : 0
> cpu cores       : 2
> apicid          : 0
> initial apicid  : 0
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 22
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
> vmx flags       : vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
> bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
> bogomips        : 7799.87
> clflush size    : 64
> cache_alignment : 64
> address sizes   : 39 bits physical, 48 bits virtual
> power management:
>

**Comment by bpetit** [comment]
To investigate further on this bug we will need data I guess. I opened an FR to be able to extract this data: https://github.com/hubblo-org/scaphandre/issues/66

Stay tuned

**Comment by bpetit** [comment]
Hi @Mathieu-Coupe !

Sorry for the long delay response !

I tried a fix that might have an incidence on this issue : #132 

Could you try that on the same machine/setup (if you still have it...) and tell me if it seems to get any better ?

**Comment by Mathieu-Coupe** [comment]
Hi !

Yes, I still have this setup (but it got updated to newer kernel in the meantime).
I installed it back from the compose file provided and the issue seems fixed 👍
I'll let it run from now.

![image](https://user-images.githubusercontent.com/1534517/139595348-f7766640-3d69-4aa0-8682-4f73270fce54.png)

There is still a minor issue. I see a spike in the socket consumption only, that goes away if I zoom a little in the graph.
![image](https://user-images.githubusercontent.com/1534517/139595413-4691b0a8-6fd9-4915-b141-6bb378ec47bd.png)

Same view when zoomed on the spike
![image](https://user-images.githubusercontent.com/1534517/139595437-b6223f46-94cf-4c5c-b7d9-ac6c6385acfa.png)

**Comment by Mathieu-Coupe** [comment]
Hi,

there is indeed something to configure on grafana level to better handle on very high spike in the data but the issue itself is that one point got a very high value.

If you look at the raw data sent by prometheus, we can see it :
![image](https://user-images.githubusercontent.com/1534517/141075359-1fbf18a0-874a-46ef-9997-c1fe46c05279.png)

For the rest, still good.

**Comment by bpetit** [comment]
Hi,

There is something to fix indeed. But this seems not specifically related to systemd, right ?

Would you mind open a new issue for that specific behavior ?

Thanks !
