### ISSUE TITLE
Different result using rate(scaph_host_energy_microjoules) and scaph_host_power_microwatts

### ISSUE THREAD

**Issue by Louan-Robert** [hubblo-org/scaphandre#325]
Hello, I am using scaphandre in one of my projects and encountering some problems.

When comparing `scaph_host_energy_microjoules` and applying prometheus `rate()` function to `scaph_host_power_microwatts`, I am getting different results.

![image](https://github.com/hubblo-org/scaphandre/assets/125887532/81cf5f67-873d-49c3-bffc-3bc5216b9bf8)

My understanding is that when applying the `rate()` function to `scaph_host_energy_microjoules` metric, the result is a graph in watt. So, the resulting graph should be the same as `scaph_host_power_microwatts`, but it is not.

Does this mean one of these metrics is more reliable than the other ? If so, which one should I use to monitor a server power consumption ?

Thanks !

**Comment by TheElectronWill** [comment]
Without checking the source code, I guess that `host_power` is the instantaneous power, whereas `energy` is the amount of energy consumed since the last measurement. The instantaneous power is unprecise, because the actual power varies between two measurements, and that changes the energy consumption. Thus, the energy should be more reliable (even if #280 should be fixed to avoid some small errors in the energy values).

**Comment by mmadoo** [comment]
In our architecture, we use 2 prometheus instances for a better reliability. So having energy between previous measurement can lead to wrong values.
Is there a way to have a [counter  ](https://prometheus.io/docs/concepts/metric_types/#counter) that gives a cumulative metric value ?

**Comment by bpetit** [comment]
Hi,

@TheElectronWill is right.
Yes, the way power is calculated may differ a bit from using microjoules then applying prometheus operators.

Using microjoules metrics may help if you want to use the prometheus operators to do the "energy counter (microjoules)" -> "power average on timeframe" conversion.
